### ISSUE TITLE
Make "knowit company" a editable dropdown

### ISSUE THREAD

**Issue by Fredrik-C** [kirayatail/kds16#1]
Having predefined values to choose from will make it easier to match hotel rooms and will provide better statistics

**Comment by kirayatail** [comment]
I found a list of company names which also included a default email address for invoices, is that enough to automatically derive invoice information based on selected company?

**Comment by Fredrik-C** [comment]
Does the list also include norwegian companies (Reaktor, Objectnet...) etc?

**Comment by kirayatail** [comment]
Yes, Norwegian, Estonian, Danish and Finnish companies, though the list was incomplete regarding invoice emails.

**Comment by Fredrik-C** [comment]
Ok, then just use the list as a "knowit company" dropdown.

**Comment by kirayatail** [comment]
fixed by 78303857696440a50
