### ISSUE TITLE
Confirmation email when submitted a talk

### ISSUE THREAD

**Issue by Fredrik-C** [kirayatail/kds16#10]
When a talk is submitted a "sign-in" mail is sent out.

I would be nice if this email would state:
"Click this link to confirm your registered talk with title [placeholder]"

**Comment by kirayatail** [comment]
should changes to an existing talk also require confirmation?

**Comment by Fredrik-C** [comment]
Hm, I suppose you will require a sign-in token to be able to edit a talk,
in that way you are already authenticated/identified and a confirmation
request is not nececary

**Comment by kirayatail** [comment]
the new Register/login process emphasizes that you need a sign-in token to create or edit anything.
